import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";

import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";
export default function Home() {
  const [darkMode, SetDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Rami Babay Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-10 lg:px-20 dark:bg-black">
        <section className="min-h-screen ">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">
              Developed by BABAY
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => SetDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:bg-white dark:rounded-xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Rami Babay
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Developer And Designer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white">
              I'm an actuel Software Developer with a scientific background(
              Bachlor cursus in Engineering Physics at Ecole Polytechnique
              Montreal and studied Ecole preparatoire Maths/Physics at Institut
              Préparatoire Aux études d'ingenieurs El Manar).
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-300">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover" alt="" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">
              Services I can offer
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              Activities and societies: Neutron Activation Analysis laboratory
              at Nuclear Department-SlowPoke
              http://www.polymtl.ca/nucleaire/LTN/index.phpActivities and
              societies: Neutron Activation Analysis laboratory at Nuclear
              Department-SlowPoke
              http://www.polymtl.ca/nucleaire/LTN/index.php…see more Classical
              Mechanics,Quantum Mechanics,Calculus,Linear Algebra,Non linear
              Algebra,Hermitian Algebra,Atomic Decay,Waves
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              Bloomberg’s industry-leading data is not only the most
              comprehensive, it’s also the most timely and accurate. So you can
              solve bigger challenges
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image
                src={design}
                className="mx-auto"
                width={100}
                height={100}
                alt=""
              />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Beautiful Designs
              </h3>
              <p className="dark:text-white">
                Design is the process of creating something with a specific
                purpose or function in mind. It encompasses a wide range of
                disciplines, including graphic design, industrial design,
                interior design, fashion design, and many more. At its core,
                design involves understanding the needs and desires of the
              </p>
              <h4 className="py-4 text-teal-600">Design tools that I use</h4>
              <p className="text-gray-800 dark:text-gray-300 py-1">Sketch</p>
              <p className="text-gray-800 dark:text-gray-300 py-1">Figma</p>
              <p className="text-gray-800 dark:text-gray-300 py-1">Canva</p>
              <p className="text-gray-800 dark:text-gray-300 py-1">Blender</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image
                src={code}
                className="mx-auto"
                width={100}
                height={100}
                alt=""
              />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Beautiful Designs
              </h3>
              <p className="dark:text-white">
                Design is the process of creating something with a specific
                purpose or function in mind. It encompasses a wide range of
                disciplines, including graphic design, industrial design,
                interior design, fashion design, and many more. At its core,
              </p>
              <h4 className="py-4 text-teal-600">Design tools that I use</h4>
              <p className="text-gray-800 dark:text-gray-300 py-1">Sketch</p>
              <p className="text-gray-800 dark:text-gray-300 py-1">Figma</p>
              <p className="text-gray-800 dark:text-gray-300 py-1">Canva</p>
              <p className="text-gray-800 dark:text-gray-300 py-1">Blender</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image
                src={consulting}
                className="mx-auto"
                width={100}
                height={100}
                alt=""
              />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Beautiful Designs
              </h3>
              <p className="dark:text-white">
                Design is the process of creating something with a specific
                purpose or function in mind. It encompasses a wide range of
                disciplines, including graphic design, industrial design,
                interior design, fashion design, and many more. At its core,
                design involves understanding the needs and desires of the
                intended audience and finding creative solutions to meet those
              </p>
              <h4 className="py-4 text-teal-600">Design tools that I use</h4>
              <p className="text-gray-800 dark:text-gray-300 py-1">Sketch</p>
              <p className="text-gray-800 dark:text-gray-300 py-1">Figma</p>
              <p className="text-gray-800 dark:text-gray-300 py-1">Canva</p>
              <p className="text-gray-800 dark:text-gray-300 py-1">Blender</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            {" "}
            <h3 className="text-3xl py-1 dark:text-white">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              Activities and societies: Neutron Activation Analysis laboratory
              at Nuclear Department-SlowPoke
              http://www.polymtl.ca/nucleaire/LTN/index.phpActivities and
              societies: Neutron Activation Analysis laboratory at Nuclear
              Department-SlowPoke
              http://www.polymtl.ca/nucleaire/LTN/index.php…see more Classical
              Mechanics,Quantum Mechanics,Calculus,Linear Algebra,Non linear
              Algebra,Hermitian Algebra,Atomic Decay,Waves
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              Bloomberg’s industry-leading data is not only the most
              comprehensive, it’s also the most timely and accurate. So you can
              solve bigger challenges
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image src={web1} alt="" className="rounded-lg object-cover" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web2} alt="" className="rounded-lg object-cover" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web3} alt="" className="rounded-lg object-cover" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web4} alt="" className="rounded-lg object-cover" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web5} alt="" className="rounded-lg object-cover" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web6} alt="" className="rounded-lg object-cover" />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
